### ISSUE TITLE
请求申请新的client_id.

### ISSUE THREAD

**Issue by Ringyuki** [ymgal/docs#1]
client_id：hikarinagi
用途：自动化获取Gal的简介信息
站点：https://www.hikarinagi.com

预计通过php实现，日均请求量50k-100k

**Comment by sorakylin** [comment]
除非每个接口都同步走一道月幕的API，否则不应该会有这么多请求。
毕竟月幕现在的API全是查询API。

还请尽可能避免每个接口都同步查询，这会降低你服务的吞吐量，也会增加月幕的负担，两边不讨好了。
建议，调用完月幕的查询API后将其保存在你的本地 —— 无论是以持久化的方式，还是临时缓存的方式。
保存后，可采取常见的缓存刷新策略实现刷新。

还请确认。

**Comment by Ringyuki** [comment]
如果缓存数据的话请求量就很小了，我应该会设置为7天左右更新一次数据，日均请求量的话1k左右吧，感谢提醒🥰🥰

**Comment by sorakylin** [comment]
没问题，你专属的 client_id 与 client_secret 会通过邮件发送。
我会使用你 Github 主页的邮箱，请确认，它是否是可用的、安全的，如果答案为否定的话，可以在这里给我你的新邮箱。

**Comment by Ringyuki** [comment]
当然，我的 Github 主页的邮箱是可用且安全的

**Comment by sorakylin** [comment]
邮件已发送
